version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/nodejs-goof # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-snyk
          command: 'sudo npm install -g snyk'     
      - run: # run snyk help - test snyk is installed and working
          name: snyk-help
          command: snyk --help
      - snyk/scan:
            fail-on-issues: false
            monitor-on-build: true
            severity-threshold: high
            token-variable: SNYK_TOKEN
